import { Lesson } from "./types";

export const LESSONS: Lesson[] = [
  {
    id: 1,
    title: "GIS as Your Field Toolkit",
    subtitle: "Layers, features, and seeing the big picture",
    gisConcepts: ["Layers", "Features", "Attributes", "Spatial Data"],
    fieldConcepts: ["Work area overview", "Issue clustering", "Resource planning"],
    conceptContent:
      "A Geographic Information System (GIS) organizes the world into **layers** -- each representing a different type of information about the same area. Your trail network is one layer. Parks are another. Waterways are another. Maintenance reports are another.\n\nEach layer contains **features** (individual objects like a specific trail or park), and each feature has **attributes** (properties like name, length, or condition). The power of GIS is in **stacking layers** to reveal patterns that are invisible when looking at any single dataset alone.\n\nWhen you toggle layers on this map, you're doing exactly what professional GIS analysts do -- combining spatial data to answer questions like \"Where do erosion problems concentrate?\" or \"Which trails near waterways need the most maintenance?\"",
    fieldContent:
      "You already think spatially every day. When you plan your route between work sites, you're optimizing a network. When you notice graffiti keeps appearing at the same trailhead, you're recognizing a spatial pattern. GIS just gives you the tools to **see, measure, and prove** what you already intuit.\n\n**Why layers matter for your job**: Toggle between trails and waterways -- notice how erosion reports concentrate where trails run close to creeks? Toggle on maintenance issues and you can instantly see which parts of the district are demanding the most attention this week. That's actionable intelligence, not just a pretty map.\n\nEvery maintenance report you file becomes a feature in the maintenance layer. Over time, your data tells a story about where the district needs investment.",
    exerciseSteps: [
      { step: 1, instruction: "Look at the map with all layers visible. You can see trails (colored lines), parks (colored dots), waterways (blue lines), and the district boundary. Each of these is a separate data layer.", mapAction: "all-layers-on" },
      { step: 2, instruction: "Turn OFF the trails layer. Notice how the map changes -- what infrastructure information disappears? Now you're seeing the landscape without the trail network.", mapAction: "toggle-trails" },
      { step: 3, instruction: "Turn OFF everything except waterways. These blue lines are the drainage network -- the creeks and rivers that cause most of your erosion headaches.", mapAction: "waterways-only" },
      { step: 4, instruction: "Turn trails back ON alongside waterways. Where do trails run parallel to or cross waterways? These intersections are where you'll see the most erosion and drainage issues.", mapAction: "trails-and-waterways" },
      { step: 5, instruction: "Turn all layers back on. You just performed your first GIS analysis: identifying spatial relationships between infrastructure and natural features that predict maintenance needs." , mapAction: "all-layers-on" },
    ],
    vocabulary: [
      { term: "GIS", definition: "Geographic Information System -- technology for capturing, storing, analyzing, and displaying location-based data. Your map app is a simplified GIS." },
      { term: "Layer", definition: "A single dataset in a GIS representing one type of geographic feature (e.g., all trails, all parks, all maintenance reports)." },
      { term: "Feature", definition: "An individual geographic object within a layer (e.g., the High Line Canal Trail is one feature in the trails layer)." },
      { term: "Attribute", definition: "A property of a feature stored in a data table (e.g., a trail's length, a maintenance report's severity, or a park's name)." },
      { term: "Spatial Data", definition: "Data that has a geographic location -- it describes both where something is and what it is." },
      { term: "Spatial Analysis", definition: "Using the location of features to find patterns, relationships, and trends -- like noticing erosion clusters near waterways." },
    ],
    quiz: [
      {
        id: "q1-1",
        question: "What is a 'layer' in GIS?",
        options: ["A physical map printed on paper", "A single dataset representing one type of geographic feature", "The color scheme of a map", "A satellite image"],
        correctIndex: 1,
        explanation: "A layer is a single dataset (like all trails or all maintenance reports) that can be overlaid with other layers to reveal spatial patterns.",
      },
      {
        id: "q1-2",
        question: "Why would you overlay trails and waterways layers together?",
        options: ["To make the map look prettier", "To find where trail infrastructure intersects with drainage, predicting erosion risk", "To count how many parks are in the district", "To measure trail elevation"],
        correctIndex: 1,
        explanation: "Trail-waterway intersections are where erosion, flooding, and drainage problems concentrate. Overlaying these layers makes those risk zones visible.",
      },
      {
        id: "q1-3",
        question: "Every maintenance report you file becomes what in GIS terms?",
        options: ["A layer", "A basemap", "A feature with attributes (location, category, severity, etc.)", "A coordinate system"],
        correctIndex: 2,
        explanation: "Each report is a feature (a point on the map) with attributes: its category, severity, description, photos, date, and your name. Over time, these features reveal maintenance patterns.",
      },
    ],
    requiredLayers: ["trails", "parks", "waterways", "district-boundary"],
  },
  {
    id: 2,
    title: "Finding the Problem",
    subtitle: "Coordinates, GPS, and navigating to work sites",
    gisConcepts: ["Coordinate Systems", "WGS84", "GPS", "Location Accuracy"],
    fieldConcepts: ["Navigating to citizen reports", "Pinpointing locations", "GPS on your phone"],
    conceptContent:
      "Every point on Earth can be described by **coordinates** -- numbers that specify a location. The system your phone uses is called **WGS84** (or EPSG:4326), which gives locations as **latitude** (north-south) and **longitude** (east-west).\n\nThe SSPR district sits roughly between **39.52\u00b0N** and **39.65\u00b0N** latitude, and **-105.08\u00b0W** and **-104.86\u00b0W** longitude. Carson Nature Center is at **39.5963\u00b0N, -105.0139\u00b0W** -- those six decimal places give you roughly 11cm precision.\n\nMove your mouse over the map and watch the coordinates change in the bottom-left corner. Every pixel on the map corresponds to a real location where you might need to respond to a maintenance request.",
    fieldContent:
      "When a citizen calls in \"there's graffiti on the Bear Creek Trail,\" that's not enough to find it. But **39.6435, -105.0210** -- that's a location you can navigate to. Coordinates are the language that turns vague reports into actionable work orders.\n\n**Your phone's GPS** receiver talks to satellites to determine your position, typically accurate to 3-10 meters. That's good enough to find a pothole or a vandalized bench, but if you're documenting a specific drainage failure, noting the coordinates helps the next crew find the exact same spot.\n\n**Pro tip**: When you log a maintenance report in the field, your phone automatically captures GPS coordinates. That's GIS data collection happening in your pocket. The more precise your location data, the better your team can analyze where problems recur.",
    exerciseSteps: [
      { step: 1, instruction: "Move your mouse across the map and watch the coordinate display in the bottom-left corner. Notice how latitude (first number) changes as you move north/south, and longitude (second number) changes east/west." },
      { step: 2, instruction: "Find Carson Nature Center on the map (the green dot along the South Platte River, grid E-6). Its coordinates are approximately 39.5963, -105.0139. Imagine a citizen reported an issue near here -- these coordinates get you there." },
      { step: 3, instruction: "Move to the northeast corner of the district, near Family Sports Center. Compare the coordinates. Latitude increased (further north), longitude became less negative (further east)." },
      { step: 4, instruction: "Think about this: if a citizen reports 'erosion on the trail near the parking lot,' how precise do those coordinates need to be? 10 meters is fine for finding the parking lot. 1 meter helps you find the exact washout." },
    ],
    vocabulary: [
      { term: "Coordinate Reference System (CRS)", definition: "A framework defining how coordinates map to real locations on Earth. Your phone uses WGS84." },
      { term: "WGS84 (EPSG:4326)", definition: "The World Geodetic System 1984 -- the standard coordinate system used by GPS. Locations are in degrees of latitude and longitude." },
      { term: "Latitude", definition: "How far north or south a point is from the equator. Denver is about 39.6\u00b0N." },
      { term: "Longitude", definition: "How far east or west a point is from the Prime Meridian. Denver is about -105.0\u00b0W (negative = west)." },
      { term: "GPS", definition: "Global Positioning System -- satellite-based navigation providing location coordinates. Consumer GPS (your phone) is typically accurate to 3-10 meters." },
      { term: "Location Accuracy", definition: "How close a GPS reading is to the true position. Matters when you need to relocate a specific problem -- like finding the exact drain that's clogged." },
    ],
    quiz: [
      {
        id: "q2-1",
        question: "What coordinate system does your phone's GPS use?",
        options: ["UTM Zone 13N", "WGS84 (EPSG:4326)", "State Plane Colorado", "Google Maps Coordinates"],
        correctIndex: 1,
        explanation: "GPS devices use WGS84, which expresses locations as latitude and longitude in degrees. This is the global standard.",
      },
      {
        id: "q2-2",
        question: "A citizen reports 'damage at coordinates 39.6200, -105.0060.' Why are coordinates more useful than 'somewhere on the trail near Cornerstone Park'?",
        options: ["Coordinates look more professional", "Coordinates let you navigate directly to the exact spot, saving search time", "Coordinates are required by law", "They aren't more useful"],
        correctIndex: 1,
        explanation: "Coordinates are unambiguous. 'Near Cornerstone Park' could mean anywhere within a half mile. Coordinates pinpoint the location to within a few meters.",
      },
      {
        id: "q2-3",
        question: "Your phone's GPS is accurate to about 3-10 meters. Is that good enough to find a reported pothole in a parking lot?",
        options: ["No, you need sub-centimeter accuracy", "Yes -- 3-10 meters gets you close enough to visually locate it", "GPS doesn't work in parking lots", "You need a survey-grade GPS"],
        correctIndex: 1,
        explanation: "3-10 meter accuracy gets you to the right area of the parking lot. From there your eyes take over. For most maintenance work, phone GPS is perfectly adequate.",
      },
    ],
    requiredLayers: ["parks", "district-boundary"],
  },
  {
    id: 3,
    title: "Logging What You Find",
    subtitle: "Points, attributes, and standardized reporting",
    gisConcepts: ["Point Geometry", "Attribute Tables", "Classification", "Symbology"],
    fieldConcepts: ["Maintenance reporting", "Issue categorization", "Data quality"],
    conceptContent:
      "**Points** are the simplest geometry type in GIS -- a single location defined by coordinates. But the power is in their **attributes**: the data attached to each point.\n\nOn the SSPR map, each park is a point feature with attributes like name, category, and grid reference. A maintenance report is also a point feature, with attributes like category (graffiti, erosion, snow), severity (low to critical), description, photos, and the reporter's name.\n\n**Classification** groups features by an attribute value -- like grouping all parks by type, or all maintenance reports by category. **Symbology** controls how each class looks on the map. When you see color-coded dots, that's classification + symbology working together to make patterns visible at a glance.",
    fieldContent:
      "Every maintenance report you file is a **point feature with attributes**. Think about it:\n\n- **Point** = GPS coordinates of the problem\n- **Category** = graffiti, erosion, snow/ice, trail surface, etc.\n- **Severity** = low, medium, high, critical\n- **Description** = what you actually see in the field\n- **Photo** = visual documentation\n- **Date/time** = when you found it\n- **Your name** = who reported it\n\nThis is an **attribute table** -- the same structure professional GIS analysts use. The difference between good data and bad data is **standardized classification**. If one person reports 'water damage' and another reports 'erosion' for the same type of problem, your data becomes messy. Consistent categories let you filter, count, and analyze.\n\nWhen your supervisor pulls up a map showing 30 red dots (critical issues) clustered on one trail segment, that's your field data driving a resource decision. **Your reports are the data.**",
    exerciseSteps: [
      { step: 1, instruction: "Make sure the Parks layer is visible. Click on different park markers to inspect their attributes in the popup -- name, category, ecological class, grid reference.", mapAction: "parks-only" },
      { step: 2, instruction: "Notice the color-coding: green dots are natural areas, blue are water-related, gray are built facilities. This is classification by category -- the same principle behind color-coding maintenance reports by type." },
      { step: 3, instruction: "Find and click on Carson Nature Center (along the South Platte River). Read its attributes. Now imagine this is a maintenance report instead -- what attributes would you want? Location, category, severity, description, photo, date, reporter." },
      { step: 4, instruction: "Compare a natural area (like South Platte Park, 880 acres) to a built facility (like a recreation center). Different categories require different maintenance approaches -- just like how your graffiti response differs from your erosion response." },
      { step: 5, instruction: "Count how many parks of each type you can find by clicking around. This counting-by-category is exactly what you do when reporting 'We had 12 erosion issues and 5 graffiti incidents this month.'" },
    ],
    vocabulary: [
      { term: "Point Feature", definition: "A geographic feature represented by a single coordinate pair. Examples: a maintenance report location, a park, a trailhead." },
      { term: "Attribute Table", definition: "A structured database storing properties of geographic features. Each row is a feature, each column is an attribute (category, severity, date, etc.)." },
      { term: "Classification", definition: "Grouping features into categories based on an attribute value (e.g., grouping maintenance reports by type: graffiti, erosion, snow)." },
      { term: "Symbology", definition: "The visual representation of features on a map -- colors, sizes, and shapes that encode information (red = critical, green = low severity)." },
      { term: "Data Quality", definition: "The accuracy and consistency of your data. Using standardized categories and complete attribute fields produces better data." },
      { term: "Standardized Classification", definition: "Using the same categories consistently so data can be analyzed reliably. 'Erosion' always means erosion, not 'water damage' or 'trail washout.'" },
    ],
    quiz: [
      {
        id: "q3-1",
        question: "What makes a point feature useful beyond just its location?",
        options: ["Its color on the map", "Its attributes -- the data properties attached to it", "How zoomed in you are", "The basemap behind it"],
        correctIndex: 1,
        explanation: "A point's real value is in its attributes: category, severity, description, photos, dates, and reporter. These let you filter, analyze, and act on the data.",
      },
      {
        id: "q3-2",
        question: "When you file a maintenance report, which part is the 'point' and which are the 'attributes'?",
        options: ["The category is the point, the location is an attribute", "The GPS coordinates are the point geometry; category, severity, description, and photos are the attributes", "Everything is a point", "The photo is the point, everything else is an attribute"],
        correctIndex: 1,
        explanation: "The GPS coordinates define the point geometry (where). Everything else -- category, severity, description, photos, date -- are attributes (what, how bad, when).",
      },
      {
        id: "q3-3",
        question: "Why is standardized classification important for maintenance reporting?",
        options: ["It's required by law", "Using consistent categories lets you count, filter, and analyze patterns across all reports", "It makes reports look professional", "It doesn't really matter"],
        correctIndex: 1,
        explanation: "If everyone uses the same categories consistently, you can answer questions like 'How many erosion issues this quarter?' and 'Where does graffiti concentrate?' Inconsistent classification makes analysis impossible.",
      },
    ],
    requiredLayers: ["parks", "district-boundary"],
  },
  {
    id: 4,
    title: "Following the Trail",
    subtitle: "Lines, distances, and locating problems along a route",
    gisConcepts: ["Polylines", "Distance Measurement", "Network Connectivity", "Linear Referencing"],
    fieldConcepts: ["Trail segment identification", "Reporting problem locations", "Route planning"],
    conceptContent:
      "**Lines** (polylines) represent linear features -- trails, roads, streams, fences. Each line is a sequence of coordinate pairs (vertices) connected in order.\n\nTwo critical GIS concepts come from line data: **distance** (how far along a trail is the problem?) and **connectivity** (does this trail connect to other trails? does this stream connect to the river?). When you say \"the washout is about a quarter mile south of the Columbine trailhead,\" you're doing **linear referencing** -- locating a point along a line by distance from a known reference.\n\n**Networks** are connected sets of lines. The SSPR trail network lets hikers (and your maintenance vehicles) move from point to point. The stream network carries water from small creeks into the South Platte River. Understanding both networks helps you predict where problems will occur.",
    fieldContent:
      "Trail lines are your daily workspace. When you describe a problem as \"0.3 miles south of the trailhead\" instead of \"somewhere on the trail,\" you're using **linear referencing** -- one of the most practical GIS skills there is.\n\n**Why this matters for maintenance**: The SSPR trail system has 14 major trails covering 55+ miles. Knowing exact distances helps your crew find the right spot without wasting time searching. It also helps you track which **trail segments** need the most attention.\n\n**Waterway networks predict your workload**: Every creek eventually drains into the South Platte River. After heavy rain, problems flow downstream -- erosion on Bear Creek can move sediment into the South Platte. Trail-waterway crossings are your highest-risk zones for washouts, flooding, and sediment buildup. If you know where trails cross creeks, you know where to check first after a storm.",
    exerciseSteps: [
      { step: 1, instruction: "Turn on both the Trails and Waterways layers. Notice that both are line features, but they represent very different networks -- human infrastructure vs. natural drainage.", mapAction: "trails-and-waterways" },
      { step: 2, instruction: "Find the South Platte River (the thickest blue line running north-south). Click it. This is the main drainage -- every creek in the district flows into it." },
      { step: 3, instruction: "Trace where Bear Creek, Big Dry Creek, and Little Dry Creek connect to the South Platte. After storms, these confluences are maintenance hotspots -- check the trails near these points first." },
      { step: 4, instruction: "Now look at the Mary Carter Greenway Trail (the trail running parallel to the South Platte). At 8.5 miles, it's the longest trail and runs right alongside the river. That proximity to water means more erosion, flooding, and drainage maintenance." },
      { step: 5, instruction: "Find places where trails cross or run close to waterways. These are your highest-priority inspection points after any significant weather event." },
    ],
    vocabulary: [
      { term: "Polyline", definition: "A GIS geometry type representing a linear feature as an ordered sequence of coordinate pairs. Trails, streams, and fences are all polylines." },
      { term: "Linear Referencing", definition: "Locating a point along a line by distance from a known reference. '0.3 miles south of the trailhead' is linear referencing." },
      { term: "Network", definition: "A connected set of linear features forming a system (e.g., a trail network you drive/walk, or a stream network carrying water)." },
      { term: "Connectivity", definition: "How features in a network are linked. Trail connectivity determines your route to a work site. Stream connectivity determines where water flows." },
      { term: "Confluence", definition: "Where two waterways meet. Confluences concentrate water volume and are maintenance hotspots for erosion and flooding." },
      { term: "Trail Segment", definition: "A specific section of a trail, often defined by intersections or landmarks. Useful for directing crews to the right location." },
      { term: "Watershed", definition: "The land area that drains water to a common point. All of SSPR drains to the South Platte River." },
    ],
    quiz: [
      {
        id: "q4-1",
        question: "After a heavy rainstorm, which locations should you check first for trail damage?",
        options: ["The longest trails", "Where trails cross or run alongside waterways", "The newest trails", "Trails with the most foot traffic"],
        correctIndex: 1,
        explanation: "Trail-waterway intersections concentrate water flow and are the highest-risk zones for erosion, washouts, and flooding. Water is the #1 driver of trail damage.",
      },
      {
        id: "q4-2",
        question: "What is 'linear referencing' and why does it help your crew?",
        options: ["Measuring the total length of all trails", "Locating a specific point along a trail by distance from a known reference, so crews can find the exact spot", "Drawing a straight line between two parks", "Counting the number of trail intersections"],
        correctIndex: 1,
        explanation: "'The erosion is 0.3 miles south of the Columbine trailhead' is linear referencing. It turns a vague location into navigable directions, saving your crew search time.",
      },
      {
        id: "q4-3",
        question: "The South Platte River is the main stem of the SSPR watershed. What does that mean for maintenance?",
        options: ["It has no effect on maintenance", "Water and sediment from every creek in the district eventually reaches it, so problems compound downstream", "Only trails along the river need maintenance", "It means the river needs to be maintained"],
        correctIndex: 1,
        explanation: "Everything in the SSPR watershed drains to the South Platte. Erosion upstream on Bear Creek deposits sediment downstream. Understanding this flow helps prioritize where maintenance has the most impact.",
      },
    ],
    requiredLayers: ["trails", "waterways", "district-boundary"],
  },
  {
    id: 5,
    title: "Zones, Boundaries & Polygons",
    subtitle: "Areas, containment, and how districts are organized",
    gisConcepts: ["Polygon Geometry", "Containment", "Area Calculation", "Administrative Boundaries"],
    fieldConcepts: ["District boundaries", "Jurisdiction awareness", "Work zones", "Park acreage"],
    conceptContent:
      "**Polygons** are closed shapes that define areas -- park boundaries, district limits, flood zones, or habitat patches. While points say *where* and lines say *how far*, polygons answer **how much space** and **what's inside**.\n\nA polygon is stored as an ordered ring of coordinates. The SSPR district boundary is one large polygon. Each park can also be represented as a polygon (though we currently show them as points for simplicity). Polygons let you ask powerful GIS questions:\n\n- **Containment**: Is this maintenance report inside the SSPR district? Which park does it fall within?\n- **Area**: How many acres is South Platte Park? What total area does the district cover?\n- **Overlay**: Where does a flood zone overlap with trail corridors?\n\nPolygon analysis is the foundation of zoning, land management, and jurisdiction -- concepts you use daily when deciding whether a reported issue is on SSPR property.",
    fieldContent:
      "You probably already have a mental map of your district boundaries. You know which trails and parks are \"yours\" and which belong to the city or county. In GIS, that mental map becomes a **polygon** -- a precise, measurable shape.\n\n**Why this matters**: When a citizen reports a problem, the first question is often \"Is this ours?\" If the report falls inside the SSPR district polygon, it's your responsibility. If it's 50 feet outside the boundary, it belongs to another agency. GIS makes this determination instant and unambiguous.\n\n**Park acreage drives resource planning**: South Platte Park is ~880 acres. A small neighborhood park might be 5 acres. The maintenance effort scales with area. By knowing park polygons and their acreage, your supervisor can allocate mowing crews, trash collection routes, and inspection schedules proportionally.\n\n**Flood zones are polygons too**: FEMA maps show flood risk as polygons. Knowing which trail segments fall within the 100-year floodplain tells you where to expect the most storm damage and where to focus post-storm inspections.",
    exerciseSteps: [
      { step: 1, instruction: "Turn on only the District Boundary layer. This polygon represents the entire SSPR service area. Everything inside this boundary is your jurisdiction.", mapAction: "parks-only" },
      { step: 2, instruction: "Now turn on all layers. Notice how every feature -- trails, parks, waterways, maintenance issues -- sits inside (or at the edge of) this boundary polygon. That containment relationship defines your work area." , mapAction: "all-layers-on" },
      { step: 3, instruction: "Click on some park markers. Look at the 'Area (Acres)' attribute. South Platte Park (~880 acres) requires vastly more maintenance than a 2-acre pocket park. Polygon area drives resource allocation." },
      { step: 4, instruction: "Zoom out to see the full district shape. Notice it's not a simple rectangle -- it follows municipal boundaries, property lines, and natural features. Real-world boundaries are rarely clean geometric shapes." },
      { step: 5, instruction: "Imagine a citizen reports an issue just outside the boundary. In GIS, a 'point in polygon' test instantly determines jurisdiction. Without GIS, you'd drive out to check, wasting an hour." },
    ],
    vocabulary: [
      { term: "Polygon", definition: "A closed shape defined by a ring of coordinate pairs, representing an area. Parks, districts, flood zones, and parcels are all polygons." },
      { term: "Containment (Point-in-Polygon)", definition: "A spatial test that determines whether a point feature (like a maintenance report) falls inside a polygon (like a park boundary)." },
      { term: "Area", definition: "The measured extent of a polygon, calculated from its coordinates. Expressed in square meters, acres, or square miles." },
      { term: "Boundary", definition: "The edge of a polygon where one zone meets another. The SSPR district boundary separates your jurisdiction from adjacent agencies." },
      { term: "Jurisdiction", definition: "The geographic area where an organization has authority. Defined by boundary polygons in GIS." },
      { term: "Overlay Analysis", definition: "Combining two polygon layers to find where they intersect -- e.g., where flood zones overlap with parks to identify flood-risk facilities." },
    ],
    quiz: [
      {
        id: "q5-1",
        question: "A citizen reports a broken bench at coordinates 39.5700, -104.9500. How does GIS help determine if SSPR is responsible?",
        options: ["Check a paper map", "Run a point-in-polygon test to see if the coordinates fall within the SSPR district boundary", "Call the citizen back and ask", "Drive out and look for an SSPR sign"],
        correctIndex: 1,
        explanation: "A point-in-polygon spatial query instantly determines whether the reported coordinates fall inside the SSPR district polygon, settling jurisdiction in seconds.",
      },
      {
        id: "q5-2",
        question: "Why does South Platte Park (~880 acres) require more maintenance resources than a 5-acre pocket park?",
        options: ["It doesn't -- all parks get equal resources", "Larger polygon area means more trails, facilities, vegetation, and space to inspect and maintain", "Because it's older", "Because it has more parking"],
        correctIndex: 1,
        explanation: "Maintenance effort scales with area. More acreage means more mowing, more trail miles, more trash collection, more infrastructure to inspect. Polygon area is a key planning metric.",
      },
      {
        id: "q5-3",
        question: "What is a polygon in GIS?",
        options: ["A straight line between two points", "A single point on the map", "A closed shape defined by a ring of coordinates, representing an area", "A type of satellite image"],
        correctIndex: 2,
        explanation: "Polygons are closed shapes that define areas. They're used to represent parks, districts, flood zones, parcels, and any other area-based feature.",
      },
    ],
    requiredLayers: ["parks", "district-boundary"],
  },
  {
    id: 6,
    title: "Reading the Terrain",
    subtitle: "Elevation, slope, and why water flows where it does",
    gisConcepts: ["Elevation", "Slope", "Aspect", "Digital Elevation Models", "Contour Lines"],
    fieldConcepts: ["Drainage prediction", "Erosion risk assessment", "Accessibility", "Storm impact zones"],
    conceptContent:
      "The earth isn't flat, and that matters for maintenance. **Elevation** data tells you how high each point is above sea level. From elevation, you can derive:\n\n- **Slope**: How steep the ground is. Steeper slopes = faster water flow = more erosion.\n- **Aspect**: Which direction a slope faces. North-facing slopes hold snow longer; south-facing slopes dry out faster.\n- **Flow direction**: Water always flows downhill. If you know the elevation of every point, you can predict exactly where water will go during a storm.\n\n**Topographic maps** (like the ArcGIS Topo basemap) show elevation using **contour lines** -- lines connecting points of equal elevation. Closely-spaced contour lines mean steep terrain; widely-spaced lines mean flat ground. Switch to the Topographic basemap to see the terrain of the SSPR district.",
    fieldContent:
      "**Terrain drives 80% of your water-related maintenance issues.** Water follows gravity -- it flows downhill, accelerates on steep slopes, and pools in flat areas. If you can read terrain, you can predict where problems will occur *before* they happen.\n\n**Practical applications for your daily work**:\n- **Erosion hotspots**: Steep trail segments near waterways erode fastest. Switch to the topo basemap and look for closely-spaced contour lines crossing trails.\n- **Ice and snow**: North-facing slopes (aspect) stay shaded longer, meaning ice persists well into spring. These are your repeat snow/ice complaint zones.\n- **Drainage failures**: Flat areas where contour lines spread apart are where water pools. If a trail runs through a low spot, expect puddles and standing water complaints.\n- **After heavy rain**: Water flows from high ground to low ground through channels (creeks and gulches). Trail sections at the bottom of steep drainages get hit hardest.\n\n**Try this**: Switch to the Topographic basemap. The brown contour lines show you the 3D shape of the land. Where lines are close together near Bear Creek or the South Platte, terrain is steep and erosion risk is high.",
    exerciseSteps: [
      { step: 1, instruction: "In the Basemap Selector (top-left), switch to 'Topographic.' Notice the brown contour lines that appear -- these show elevation. Where lines are close together, the terrain is steep." },
      { step: 2, instruction: "Turn on trails and waterways. Look at where trails cross steep terrain (closely-spaced contour lines). These are your highest erosion risk zones." , mapAction: "trails-and-waterways" },
      { step: 3, instruction: "Find the South Platte River corridor. The river sits at the lowest elevation in the district (the valley floor). All water in the district flows toward this river -- that's why trails along it flood first." },
      { step: 4, instruction: "Now switch to the Satellite basemap and compare. You can see vegetation patterns that follow terrain -- denser trees in river valleys, open grass on higher ground. Terrain shapes the landscape." },
      { step: 5, instruction: "Think about your last week of work: which issues were water-related? Now look at the terrain near those locations. Could you have predicted the problem by reading the topo map?" },
    ],
    vocabulary: [
      { term: "Elevation", definition: "Height above sea level, measured in feet or meters. Denver is at ~5,280 feet. The South Platte River valley is the lowest point in the SSPR district." },
      { term: "Slope", definition: "The steepness of the ground, usually measured in degrees or percent. Steep slopes accelerate water flow and increase erosion risk." },
      { term: "Aspect", definition: "The compass direction a slope faces. North-facing slopes are shaded and hold moisture/ice longer; south-facing slopes dry out faster." },
      { term: "Contour Line", definition: "A line on a map connecting points of equal elevation. Closely-spaced contours = steep terrain. Widely-spaced contours = flat ground." },
      { term: "Digital Elevation Model (DEM)", definition: "A grid of elevation values covering an area, used to calculate slope, aspect, and water flow direction." },
      { term: "Drainage", definition: "The pattern of water flow across terrain. Water flows from high elevation to low elevation, following the steepest path downhill." },
    ],
    quiz: [
      {
        id: "q6-1",
        question: "On a topographic map, what do closely-spaced contour lines indicate?",
        options: ["Flat terrain", "A body of water", "Steep terrain with high erosion risk", "A parking lot"],
        correctIndex: 2,
        explanation: "Closely-spaced contour lines mean the elevation is changing rapidly over a short distance -- that's steep terrain. Steep slopes near trails are your highest erosion risk areas.",
      },
      {
        id: "q6-2",
        question: "Why do north-facing slopes generate more snow/ice complaints in winter?",
        options: ["They get more snow", "They face away from the sun, staying shaded and cold longer, so ice persists", "They're steeper", "They don't -- complaints are equal everywhere"],
        correctIndex: 1,
        explanation: "Aspect matters. North-facing slopes get less direct sunlight, especially in winter. Ice and snow persist longer on these slopes, generating repeated complaints even after south-facing areas have melted clear.",
      },
      {
        id: "q6-3",
        question: "After a heavy rainstorm, which trail segments should you inspect first based on terrain?",
        options: ["The flattest trails", "Trail segments at the bottom of steep drainages near waterways", "Trails on hilltops", "It doesn't matter -- check them all equally"],
        correctIndex: 1,
        explanation: "Water flows downhill and concentrates at the base of steep drainages. Trail segments where steep slopes meet waterways receive the highest water volume and are most likely to experience washouts, flooding, and sediment buildup.",
      },
    ],
    requiredLayers: ["trails", "waterways", "district-boundary"],
  },
  {
    id: 7,
    title: "Making Data Visual",
    subtitle: "Thematic mapping, color ramps, and telling stories with your data",
    gisConcepts: ["Thematic Mapping", "Graduated Symbols", "Color Ramps", "Map Legend"],
    fieldConcepts: ["Severity visualization", "Status dashboards", "Pattern recognition", "Reporting to supervisors"],
    conceptContent:
      "Raw data in a spreadsheet is hard to interpret. But put that same data on a map with meaningful colors, sizes, and labels, and patterns jump out instantly. That's **thematic mapping** -- using visual properties to represent data values.\n\nCommon thematic techniques you already see on this map:\n\n- **Color-coding**: Maintenance issues use red/orange/yellow/green to represent severity. Trails use different colors per route. Parks use colors per category.\n- **Graduated symbols**: Critical issues appear as larger dots than low-severity ones. Size encodes importance.\n- **Classification schemes**: Issues grouped into 10 categories, each labeled and filterable.\n\nA good thematic map lets any viewer -- your supervisor, a city council member, a fellow crew member -- understand the data **at a glance** without reading a spreadsheet. When you show a map of 30 red dots clustered on one trail segment, the case for resource allocation makes itself.",
    fieldContent:
      "**You're already making thematic maps when you report to your supervisor.** \"We had a bunch of erosion issues this month\" is a verbal summary. A thematic map showing erosion reports as orange/red dots clustered along Bear Creek is a *visual argument* for allocating resources there.\n\n**How to use thematic mapping in your daily work**:\n\n1. **Severity view**: Filter the Work Queue by severity. The map's red (critical) vs. green (low) dots instantly show you where to focus today.\n2. **Category view**: Filter by 'erosion' or 'graffiti' to see if one type of problem clusters in specific areas. If graffiti concentrates at three trailheads, that suggests those trailheads need cameras or better lighting.\n3. **Status view**: Toggle between 'New' and 'Resolved' to see your team's progress. Unresolved issues concentrated in one area? That area needs more crew time.\n4. **Temporal patterns**: Are issues from this month different from last month? Seasonal shifts (snow in winter, erosion in spring, vegetation in summer) create different map patterns.\n\n**The maintenance layer on your map IS a thematic map.** Every time you filter by category or sort by severity, you're performing thematic analysis.",
    exerciseSteps: [
      { step: 1, instruction: "Make sure the Maintenance Issues layer is visible. The colored dots are a thematic map -- severity is encoded as color (red=critical, orange=high, yellow=medium, green=low) and size.", mapAction: "all-layers-on" },
      { step: 2, instruction: "Click on several maintenance issue dots. Compare a red (critical) issue to a green (low) issue. The visual hierarchy lets you triage at a glance -- your eye is drawn to the reds first." },
      { step: 3, instruction: "Open the Work Queue (Tasks tab on mobile). Filter by 'Erosion / Washout' category. Now look at the map -- do the erosion issues cluster near waterways? This is thematic analysis revealing a spatial pattern." },
      { step: 4, instruction: "Switch the filter to 'Graffiti / Vandalism.' Do these issues cluster differently than erosion? They likely concentrate near trailheads and parking lots -- urban access points, not natural features." },
      { step: 5, instruction: "Imagine presenting this map to your supervisor. 'The red dots show 8 critical issues along Bear Creek this month.' That one sentence, backed by a visual, is worth more than a 2-page report." },
    ],
    vocabulary: [
      { term: "Thematic Map", definition: "A map that uses visual properties (color, size, shape) to represent data values. Your maintenance map is a thematic map of severity and category." },
      { term: "Graduated Symbol", definition: "A mapping technique where symbol size represents a data value. Larger dots = more critical issues." },
      { term: "Color Ramp", definition: "A sequence of colors representing a range of values. Red-orange-yellow-green severity scale is a color ramp." },
      { term: "Classification Scheme", definition: "The method for grouping data values into categories for mapping. Your 10 issue categories are a classification scheme." },
      { term: "Choropleth", definition: "A thematic map where areas (polygons) are shaded based on a data variable. Not used here yet, but common in census and land-use mapping." },
      { term: "Visual Hierarchy", definition: "Arranging map elements so the most important features stand out. Red critical issues draw the eye before green low-severity ones." },
    ],
    quiz: [
      {
        id: "q7-1",
        question: "Why are maintenance issues color-coded by severity instead of shown as identical dots?",
        options: ["It looks better", "Color-coding lets you visually triage -- critical (red) issues stand out immediately, enabling faster prioritization", "It's required by SSPR policy", "The computer chose random colors"],
        correctIndex: 1,
        explanation: "Thematic mapping uses visual properties to encode data values. Color-coding severity lets you scan the map and instantly identify critical issues without reading each one individually.",
      },
      {
        id: "q7-2",
        question: "You notice that most graffiti reports cluster near trailheads and parking lots. What does this spatial pattern suggest?",
        options: ["Coincidence", "These high-access urban locations attract vandalism -- consider cameras, lighting, or more frequent patrols at these points", "The data is wrong", "Graffiti only happens near roads"],
        correctIndex: 1,
        explanation: "Spatial patterns in thematic maps reveal causes. Graffiti concentrates where public access is easy -- trailheads, parking lots, underpasses. This pattern informs prevention strategies.",
      },
      {
        id: "q7-3",
        question: "What makes a thematic map more effective than a spreadsheet for reporting to your supervisor?",
        options: ["Nothing -- spreadsheets are always better", "Maps show spatial patterns at a glance that would require analyzing hundreds of rows in a spreadsheet", "Maps are legally required", "Supervisors can't read spreadsheets"],
        correctIndex: 1,
        explanation: "A thematic map converts rows of data into a visual story. Clusters, patterns, and outliers are immediately visible. '30 red dots on Bear Creek' is instantly compelling.",
      },
    ],
    requiredLayers: ["trails", "parks", "waterways", "district-boundary", "maintenance-issues"],
  },
  {
    id: 8,
    title: "Buffers & Proximity",
    subtitle: "Measuring how close things are and why it matters",
    gisConcepts: ["Buffer Analysis", "Proximity", "Spatial Join", "Distance Measurement"],
    fieldConcepts: ["Waterway setbacks", "Impact zones", "Prioritizing inspections", "Environmental compliance"],
    conceptContent:
      "A **buffer** is a zone of specified distance around a feature. Draw a 100-foot buffer around a creek, and you get a polygon representing everything within 100 feet of that waterway. Buffers answer the essential GIS question: **\"What is near this?\"**\n\nBuffers convert distance relationships into polygons you can analyze:\n\n- **Feature-to-feature proximity**: Which maintenance issues are within 200 feet of a waterway? (These might need environmental review.)\n- **Service area**: What trails are within a 5-minute walk of a parking lot?\n- **Impact zone**: If a chemical spill occurs at this point, what's within the affected radius?\n\n**Spatial joins** combine buffer analysis with attribute data: \"Give me all critical-severity erosion issues within 100 feet of a waterway.\" This query combines proximity (buffer), attributes (severity = critical, category = erosion), and containment -- three GIS concepts working together.",
    fieldContent:
      "**Buffers are one of the most practical GIS tools for your job.** Here's how proximity analysis applies daily:\n\n**Waterway buffers (riparian setbacks)**: Many regulations require maintenance within a certain distance of waterways to follow special procedures -- erosion control measures, sediment barriers, restoration standards. A 100-foot buffer around every waterway in the district instantly shows you which work sites need extra care.\n\n**Issue proximity to infrastructure**: If three erosion reports cluster within 200 feet of the same trail-creek crossing, that's not three separate problems -- it's one systemic drainage failure. Proximity analysis groups related issues.\n\n**Post-storm inspections**: After a flood event, you can buffer the affected waterway by 300 feet and ask \"Which trails and facilities fall within this impact zone?\" Instead of checking everything, you check only what's in the zone.\n\n**Practical distance questions you answer every day**:\n- \"Is this erosion close enough to the creek to need a sediment fence?\" (Buffer analysis)\n- \"Which parking lot is nearest to this trail damage?\" (Nearest-feature analysis)\n- \"How many issues are within walking distance of the Bear Creek trailhead?\" (Point-in-buffer query)",
    exerciseSteps: [
      { step: 1, instruction: "Turn on Trails, Waterways, and Maintenance Issues. Visually identify maintenance issues that appear close to waterways -- within about a quarter inch on screen.", mapAction: "all-layers-on" },
      { step: 2, instruction: "Click on an erosion or trail surface issue near a waterway. Read its coordinates. Now mentally draw a circle around it -- everything within that circle is 'in proximity.' That mental circle is a buffer." },
      { step: 3, instruction: "Imagine you could draw a 100-foot buffer around every waterway (blue line). That ribbon-shaped polygon would highlight every piece of infrastructure in the riparian zone. Issues inside this ribbon need environmental consideration." },
      { step: 4, instruction: "Find a cluster of 2-3 maintenance issues close together. Their proximity suggests a shared root cause -- maybe a drainage problem, a design flaw, or heavy foot traffic. Clustering IS proximity analysis." },
      { step: 5, instruction: "Think about how you'd answer: 'How many critical issues are within 500 feet of the South Platte River?' With buffers, the GIS answers that in seconds. Without GIS, you'd measure distances one by one on paper." },
    ],
    vocabulary: [
      { term: "Buffer", definition: "A polygon zone of specified distance around a feature. A 100-foot buffer around a creek creates a 100-foot-wide ribbon along both sides." },
      { term: "Proximity Analysis", definition: "Measuring and analyzing the distance between features. 'What is near this?' is the core proximity question." },
      { term: "Spatial Join", definition: "Combining attributes from two layers based on their spatial relationship (containment, proximity, intersection). 'Which issues are within the flood zone?' is a spatial join." },
      { term: "Riparian Buffer", definition: "A setback zone along a waterway where special land management rules apply. Typically 50-150 feet on each side." },
      { term: "Nearest Feature", definition: "Finding the closest feature to a given point. 'Which trailhead is nearest to this damage?' is a nearest-feature query." },
      { term: "Cluster Analysis", definition: "Identifying groups of features that are closer together than expected. Issue clusters suggest shared root causes." },
    ],
    quiz: [
      {
        id: "q8-1",
        question: "What does a 100-foot buffer around a waterway show you?",
        options: ["The depth of the water", "The speed of the current", "A zone representing everything within 100 feet of the waterway -- useful for identifying work sites that need environmental precautions", "The water temperature"],
        correctIndex: 2,
        explanation: "A buffer creates a measurable zone of proximity. A 100-foot waterway buffer identifies all trails, facilities, and maintenance issues within that sensitive riparian zone.",
      },
      {
        id: "q8-2",
        question: "Three erosion reports cluster within 200 feet of the same trail-creek crossing. What does this proximity suggest?",
        options: ["Three separate, unrelated problems", "A systemic drainage failure at that crossing -- the root cause is the infrastructure, not the individual erosion spots", "The reporters are confused", "The trail needs to be closed permanently"],
        correctIndex: 1,
        explanation: "Proximity clusters suggest shared root causes. Three erosion reports near the same crossing point to a design or drainage problem at that location, not three independent failures.",
      },
      {
        id: "q8-3",
        question: "After a flood, how would GIS buffers help you plan your inspection route?",
        options: ["They wouldn't help", "Buffer the affected waterway, then query which trails and facilities fall within the impact zone to inspect only those areas", "You should inspect everything regardless", "Buffers only work for droughts"],
        correctIndex: 1,
        explanation: "Buffering the flooded waterway creates an impact zone. Querying which assets fall within that zone gives you a focused inspection list instead of checking everything in the district.",
      },
    ],
    requiredLayers: ["trails", "waterways", "maintenance-issues", "district-boundary"],
  },
];
